---
abstract: 'Generate Animated PNG (APNG) files from individual PNG images'
author:
  - 'APNG Generator Author <nadim.khemir@gmail.com>'
build_requires:
  File::Temp: '0'
  Test::More: '0.98'
configure_requires:
  Module::Build: '0.42'
dynamic_config: 1
generated_by: 'Module::Build version 0.4234, CPAN::Meta::Converter version 2.150010'
keywords:
  - apng
  - animated
  - png
  - image
  - animation
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Image-APNG
provides:
  Image::APNG:
    file: lib/Image/APNG.pm
    version: v1.0.0
requires:
  Image::Magick: '0'
  perl: '5.010'
  strict: '0'
  warnings: '0'
resources:
  bugtracker: https://github.com/nkh/Image-APNG/issues
  license: http://dev.perl.org/licenses/
  repository: https://github.com/nkh/Image-APNG
version: v1.0.0
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
